echo "What can I do to help you today?"

echo "1.Register my path in the config file"
echo "2.View the list of routes registered in the file"
echo "3.Record the size of the files"
echo "4.Checking the size of files based on sensitivity"
echo "5.Change sensitivity value"
echo "6.Remove item by Index"
echo "0.Exit"
echo "|=================================================|"
